### ISSUE TITLE
Xhtml files under /resources/ui/ can not be read

### ISSUE THREAD

**Issue by Pilpin** [melloware/quarkus-faces#209]
Hello, 

When I run the project and try to go to a page under the **/ui/** folder, I get the following error :
```
java.lang.IllegalStateException: Internal error: file /ui/input/autoComplete.xhtml could not be read
	at org.primefaces.showcase.util.ShowcaseUtil.getFileContent(ShowcaseUtil.java:86)
	at org.primefaces.showcase.util.ShowcaseUtil.getFilesContent(ShowcaseUtil.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.apache.el.parser.AstFunction.getValue(AstFunction.java:199)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	[...]
Caused by: java.lang.IllegalStateException: Internal error: file /ui/input/autoComplete.xhtml could not be read
	at org.primefaces.showcase.util.FileContentMarkerUtil.readFileContent(FileContentMarkerUtil.java:92)
	at org.primefaces.showcase.util.ShowcaseUtil.getFileContent(ShowcaseUtil.java:77)
	[...]
Caused by: java.io.FileNotFoundException: File /org/primefaces/showcase/view/input/AutoCompleteView.java could not be found
	at org.primefaces.showcase.util.FileContentMarkerUtil.createFileContent(FileContentMarkerUtil.java:187)
	at org.primefaces.showcase.util.FileContentMarkerUtil.addBean(FileContentMarkerUtil.java:158)
	at org.primefaces.showcase.util.FileContentMarkerUtil.readFileContent(FileContentMarkerUtil.java:129)
	at org.primefaces.showcase.util.FileContentMarkerUtil.readFileContent(FileContentMarkerUtil.java:86)
	[...]
```

What's weirder : I copied the **getStarted.xhtml** file from **/resources** to **/resources/ui** and even **/resources/ui/test** and it worked without error.

Is it working for you ? Could it have something to do with my setup ? I ran the project from my IntelliJ (latest version) on a windows 11 computer.

Thank you !

**Comment by Pilpin** [comment]
I just did and it worked, no idea of what was wrong, sorry for the false alarm.
Thank you !
