### ISSUE TITLE
Warnings Question

### ISSUE THREAD

**Issue by gesker** [melloware/quarkus-faces#254]
GraalVM is issuing a lot of reflection related warnings

Warning: Could not resolve xyz.somepackage_ClientProxy for reflection configuration. Reason: java.lang.ClassNotFoundException: xyz.somepackage_ClientProxy_ClientProxy.

is there a clean way to have GraalVM work around these classes without warnings? Or, really, handle these better?

I'm guessing "--initialize-at-run-time" would NOT be the way to go as I could see one quickly hitting a point where there would just be too many command line parameters.

**Comment by melloware** [comment]
You can add `@RegisterForRelefction` on any class you want registered

**Comment by gesker** [comment]
Yes. I just pulled the repo fresh and it is set to 3.0.0.Beta1.

Would the @RegisterForRelefction have to be added upstream in the
primefaces and omnifaces project?
Would those projects consider adding that annotation as too
"quarkus" specific?

Or, is there a config file - xml descriptor or similar - we could feed to
graalvm to register all of these classes?
Or, maybe the pattern of *_ClientProxy?

**Comment by melloware** [comment]
if you can give me an example class that is not registered I need to add them to the PF Extension so they get registered.

**Comment by melloware** [comment]
That is really weird the Faces stuff is all already registered by the MyFaces extension and all the PF stuff is already registered.

As for showcase that is also wrong as I already have this on the `Book` class.

```
@RegisterForReflection
public class Book implements Serializable {
```

So I think something is wrong.  this is all working with 2.16.4 so something tells me Beta1 might have an issue with it

**Comment by melloware** [comment]
Interesting I just pulled the latest code and on Windows I am getting this...

This was all working with a previous 3.0.0.Alpha.

```
Fatal error: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 34
META-INF/resources/resources\demo\images\product\galaxy-earrings.jpg
                                  ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.escape(Pattern.java:2608)
        at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.makeResourcePattern(ResourcesFeature.java:289)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.compilePatterns(ResourcesFeature.java:282)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:270)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

**Comment by melloware** [comment]
Opened: https://github.com/quarkusio/quarkus/issues/32272

**Comment by melloware** [comment]
OK @gesker i just built the latest Quarkus Faces using my Linux machine instead of Windows and the native image built fine and worked out of the box.  So not sure exaclty all the issues you are having?

**Comment by gesker** [comment]
I'm good to go on CR1

**Comment by melloware** [comment]
OK I just updated PF and OF extensions to CR1 and deployed to Maven Central.
