### ISSUE TITLE
Freya JS seems to be not initialized

### ISSUE THREAD

**Issue by zeppelinux** [melloware/quarkus-faces#274]
I have layout.js and prism.js in resources/META-INF/resources/freya-layout/js folder. I can see both scripts are fetched by the browser, but it doesn't look like they are actually used on the page.

How I can see they are not initialized:

1. When i put console.log() in init like this:

```
PrimeFaces.widget.Freya = PrimeFaces.widget.BaseWidget.extend({

    init: function(cfg) {
        this._super(cfg);
        this.wrapper = $(document.body).children('.layout-wrapper');
        var $this = this;

        $(function() {
            $this._init();
        });

        this.restoreMenuState();
        this.expandedMenuitems = this.expandedMenuitems||[];
        console.log('PrimeFaces.widget.Freya initialized');
    }
```
There is no output in the Chrome console.

2. Freya demo (https://www.primefaces.org/freya/) has the Search icon in the top bar, it changes when clicked on. The functionality is defined in Freya's layout.js. When i copy the same topbar.hxtml to my app - nothing happens onclick. User profile menu (activated on the user image) is not activated on click as well.
3. When both Freya's layout.js & prism.js are commented out in my template.xhtml - there is no visual or functional change to my app. 

When I put both .js files in the <h:head> section of template.xhtml (as it is in Freya distribution) the console shows this error:

Uncaught ReferenceError: PrimeFaces is not defined
    at layout.js.xhtml?ln=freya-layout:4:1
(anonymous) @ layout.js.xhtml?ln=freya-layout:4

**Comment by melloware** [comment]
Sounds like they are not being loaded. How are you loading the scripts in your XHMTL?  Can you post that please?

**Comment by zeppelinux** [comment]
They are at the bottom of template.xml:

```
        <h:outputScript name="js/layout.js" library="freya-layout" />
        <h:outputScript name="js/prism.js" library="freya-layout"/>
        <h:outputScript name="jquery/jquery.js" library="primefaces" target="head"/>
        <h:outputScript name="jquery/jquery-plugins.js" library="primefaces" target="head"/>
        <h:outputScript name="locales/locale-en.js" library="primefaces" target="head"/>
        <h:outputStylesheet name="css/primeicons.css" library="freya-layout" />
        <h:outputStylesheet name="css/primeflex.min.css" library="freya-layout" />
        <h:outputStylesheet name="css/layout-dark.css" library="freya-layout" />
        <h:outputStylesheet name="css/collar_club.css"/>
    </h:body>
</f:view>
</html>
```
I can see Chrome loads them
<img width="644" alt="Screenshot 2023-05-10 at 6 24 01 PM" src="https://github.com/melloware/quarkus-faces/assets/787005/96186603-88ca-41e3-8418-424bf3dcb820">

**Comment by melloware** [comment]
In Quarkus Faces I have `target="head"` for all of them I noticed you are missing that?

```xml
        <h:outputScript name="script/layout.js" library="showcase" target="head"/>
        <h:outputScript name="showcase/script/prism.js" target="head"/>
        <h:outputScript name="jquery/jquery.js" library="primefaces" target="head"/>
        <h:outputScript name="jquery/jquery-plugins.js" library="primefaces" target="head"/>
        <h:outputScript name="locales/locale-#{app.locale.language}.js" library="primefaces" target="head"/>
    </f:view>
```

**Comment by zeppelinux** [comment]
I added target="head" to both of them, no change.

**Comment by melloware** [comment]
Hmmm tough for me to debug your issue but I am not having the same issues with any of my apps.

**Comment by zeppelinux** [comment]
Added you to my project. Need to build and install jar to mvn repo this library locally https://github.com/zeppelinux/core-lib-java/tree/feature/port-to-jakarta because of this https://github.com/apimatic/core-lib-java/issues/66

**Comment by melloware** [comment]
Yep your code is in the wrong place I just verified.  Take another look at Quarkus Faces where JS and CSS lives.

Yours (incorrect):
`src/main/resources/META-INF/resources/freya-layout`

Correct:
`src/main/resources/META-INF/resources/resources/freya-layout`

**Comment by melloware** [comment]
Think of `src/main/resources/META-INF/resources` being just `src/main/webapp` in your old app.  All of the structure under `webapp` is what goes in there.

**Comment by zeppelinux** [comment]
I refactored the project in feature/fix-resources-location branch. Now it fails on 
`2023-05-11 15:52:51,265 ERROR [io.und.req.io] (executor-thread-4) Exception handling request 11543f44-ee4c-45d3-909a-0a78d8c39b21-1 to /jakarta.faces.resource/css/layout-dark.css.xhtml: java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null`

but I can see it is loaded in Chrome inspector. It also has some RES_NOT_FOUD resource it tries to load, not sure if it's related
<img width="676" alt="Screenshot 2023-05-11 at 3 55 56 PM" src="https://github.com/melloware/quarkus-faces/assets/787005/eed781f7-71b1-4d7f-80f1-981bd419d3fa">

Can be reproduced by loading error page (i added all the .js and .css resources there)  http://localhost:8080/error/error.xhtml

**Comment by melloware** [comment]
Yep RES_NOTFOUND is a bad url and it's related. Just study exactly what Quarkus Faces is doing and don't deviate.

**Comment by zeppelinux** [comment]
Without changing anything else in the Quarkus Faces I 
1. added freya-layout at the same level as showcase and demo
2. copied the freya-layout-dark.css generated by the dart plugin in my project
3. added this resource to the template.xhtml

<img width="1335" alt="Screenshot 2023-05-12 at 12 55 43 PM" src="https://github.com/melloware/quarkus-faces/assets/787005/beb4b15d-79da-4f72-874f-cd8a0c2c012e">

The same error is logged when loading http://localhost:8081/error.xhtml

```
2023-05-12 12:54:50,142 ERROR [io.und.req.io] (executor-thread-3) Exception handling request ce46efdb-9fb3-481e-8c30-cd2b5533e1d3-1 to /jakarta.faces.resource/css/layout-dark.css.xhtml: java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
        at org.apache.myfaces.resource.ValueExpressionFilterInputStream.read(ValueExpressionFilterInputStream.java:134)
        at java.base/java.io.InputStream.read(InputStream.java:293)
        at java.base/java.io.InputStream.read(InputStream.java:218)
        at org.apache.myfaces.application.ResourceHandlerImpl.pipeBytes(ResourceHandlerImpl.java:647)
```



Looks like there is some problem with the css file produced by the dart-sass-maven-plugin. Not sure where to go from here...

**Comment by melloware** [comment]
Dart SASS is working for me...try taking Dart SASS out of it and just using the freya-layout CSS

**Comment by zeppelinux** [comment]
Fails with layout-dark.css from freya.4.1.0 distribution [(attaching)] (remove .zip extension). Does it work for you?
[layout-dark.css.zip](https://github.com/melloware/quarkus-faces/files/11467489/layout-dark.css.zip)

**Comment by melloware** [comment]
let me try

**Comment by melloware** [comment]
works fine.  I dropped it into `src\main\resources\META-INF\resources\resources\showcase\css` and then added this to my template.xhtml.

```xml
<h:outputStylesheet name="css/layout-dark.css" library="showcase"/>
```

Loaded just fine.

![image](https://github.com/melloware/quarkus-faces/assets/4399574/68a789b7-7f75-4397-a2b5-201fa7644302)

And I know it loaded because now my screen has dark background.

![image](https://github.com/melloware/quarkus-faces/assets/4399574/bc55fcf8-0547-4a3e-b3c0-965417eea407)

**Comment by zeppelinux** [comment]
I did the same, i see it is loaded
<img width="1087" alt="Screenshot 2023-05-12 at 1 35 22 PM" src="https://github.com/melloware/quarkus-faces/assets/787005/c6355e45-6a28-4926-9eb1-406fa25562da">

And there is also exception in the log (loading the error.xhtml):

```
2023-05-12 13:31:58,148 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-faces 12.0.2 on JVM (powered by Quarkus 3.0.3.Final) started in 7.991s. Listening on: http://localhost:8081
2023-05-12 13:31:58,151 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-05-12 13:31:58,151 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [awt, cache, cdi, hibernate-validator, itext, myfaces, omnifaces, poi, primefaces, primefaces-extensions, resteasy, resteasy-jackson, servlet, smallrye-context-propagation, smallrye-health, vertx, websockets, websockets-client]
2023-05-12 13:32:11,676 ERROR [io.und.req.io] (executor-thread-2) Exception handling request b0eb3cdc-1201-4124-a72a-00a2beca1098-1 to /jakarta.faces.resource/css/layout-dark.css.xhtml: java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
        at org.apache.myfaces.resource.ValueExpressionFilterInputStream.read(ValueExpressionFilterInputStream.java:134)
        at java.base/java.io.InputStream.read(InputStream.java:293)
        at java.base/java.io.InputStream.read(InputStream.java:218)
        at org.apache.myfaces.application.ResourceHandlerImpl.pipeBytes(ResourceHandlerImpl.java:647)
        at org.apache.myfaces.application.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:590)
        at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
        at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:87)
        at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
        at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
        at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
        at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
        at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
        at jakarta.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:72)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:215)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:123)
        at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:624)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:124)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$2.run(UndertowDeploymentRecorder.java:439)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by melloware** [comment]
Yep because inside the CSS all the resources are coming back NULL

```
.help-page .help-search {
  background-image: url("#{resource['freya-layout:images/pages/search.png']}");
  padding: 0;
  text-align: center;
}
```

It can't resolve that resource image.

**Comment by zeppelinux** [comment]
That was it for this error, Thanks a Lot! I would expect it to fail on images/pages/search.png though..
