### ISSUE TITLE
Docker JVM Runtime Error

### ISSUE THREAD

**Issue by dengbingaliyun** [melloware/quarkus-faces#282]
```
mvn clean package -Ddocker

docker run -i --rm -p 8081:8081 melloware/quarkus-faces:latest
```

logs list below:

```
2023-06-07 14:24:31 INFO exec  java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
2023-06-07 14:24:31 Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
2023-06-07 14:24:34 __  ____  __  _____   ___  __ ____  ______ 
2023-06-07 14:24:34  --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
2023-06-07 14:24:34  -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
2023-06-07 14:24:34 --\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-06-07 14:24:34 2023-06-07 06:24:33,716 INFO  [org.apa.myf.web.MyFacesContainerInitializer] (main) Using org.apache.myfaces.webapp.MyFacesContainerInitializer
2023-06-07 14:24:34 2023-06-07 06:24:33,719 INFO  [org.omn.ApplicationInitializer] (main) Using OmniFaces version 4.1
2023-06-07 14:24:34 2023-06-07 06:24:34,302 SEVERE [org.apa.myf.web.FacesInitializerImpl] (main) An error occured while initializing MyFaces: Unable to get listed resource java\org\primefaces\showcase\convert\CountryConverter.java from directory  for path  from underlying manager io.undertow.server.handlers.resource.ClassPathResourceManager@5c059a68: java.lang.RuntimeException: Unable to get listed resource java\org\primefaces\showcase\convert\CountryConverter.java from directory  for path  from underlying manager io.undertow.server.handlers.resource.ClassPathResourceManager@5c059a68
2023-06-07 14:24:34     at io.quarkus.undertow.runtime.KnownPathResourceManager$DirectoryResource.list(KnownPathResourceManager.java:151)
2023-06-07 14:24:34     at io.undertow.server.handlers.resource.CachedResource.list(CachedResource.java:110)
2023-06-07 14:24:34     at io.undertow.servlet.spec.ServletContextImpl.getResourcePaths(ServletContextImpl.java:271)
2023-06-07 14:24:34     at org.apache.myfaces.context.servlet.ServletExternalContextImplBase.getResourcePaths(ServletExternalContextImplBase.java:143)
2023-06-07 14:24:34     at org.apache.myfaces.config.DefaultFacesConfigurationProvider.getFacesFlowFacesConfig(DefaultFacesConfigurationProvider.java:566)
2023-06-07 14:24:34     at org.apache.myfaces.config.DefaultFacesConfigurationMerger.getFacesConfigData(DefaultFacesConfigurationMerger.java:112)
2023-06-07 14:24:34     at org.apache.myfaces.config.FacesConfigurator.configure(FacesConfigurator.java:468)
2023-06-07 14:24:34     at org.apache.myfaces.webapp.FacesInitializerImpl.buildConfiguration(FacesInitializerImpl.java:382)
2023-06-07 14:24:34     at org.apache.myfaces.webapp.FacesInitializerImpl.initContainerIntegration(FacesInitializerImpl.java:709)
2023-06-07 14:24:34     at org.apache.myfaces.webapp.FacesInitializerImpl.initFaces(FacesInitializerImpl.java:179)
2023-06-07 14:24:34     at org.apache.myfaces.core.extensions.quarkus.runtime.QuarkusFacesInitializer.initFaces(QuarkusFacesInitializer.java:63)
2023-06-07 14:24:34     at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:54)
2023-06-07 14:24:34     at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:184)
2023-06-07 14:24:34     at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
2023-06-07 14:24:34     at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
2023-06-07 14:24:34     at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
2023-06-07 14:24:34     at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
2023-06-07 14:24:34     at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:602)
2023-06-07 14:24:34     at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:251)
2023-06-07 14:24:34     at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:543)
2023-06-07 14:24:34     at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy_8(Unknown Source)
2023-06-07 14:24:34     at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy(Unknown Source)
2023-06-07 14:24:34     at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
2023-06-07 14:24:34     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-06-07 14:24:34     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
2023-06-07 14:24:34     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-06-07 14:24:34     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2023-06-07 14:24:34     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2023-06-07 14:24:34     at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
2023-06-07 14:24:34     at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
2023-06-07 14:24:34     at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
2023-06-07 14:24:34     at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2023-06-07 14:24:34     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-07 14:24:34     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-06-07 14:24:34     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-07 14:24:34     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-06-07 14:24:34     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
2023-06-07 14:24:34     at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
2023-06-07 14:24:34 
2023-06-07 14:24:34 Initialized ShowcaseCacheProvider with Caffeine
2023-06-07 14:24:35 2023-06-07 06:24:35,130 INFO  [io.quarkus] (main) quarkus-faces 13.0.0 on JVM (powered by Quarkus 3.1.0.Final) started in 3.052s. Listening on: http://0.0.0.0:8081
2023-06-07 14:24:35 2023-06-07 06:24:35,131 INFO  [io.quarkus] (main) Profile prod activated. 
2023-06-07 14:24:35 2023-06-07 06:24:35,131 INFO  [io.quarkus] (main) Installed features: [awt, cache, cdi, hibernate-validator, itext, myfaces, omnifaces, poi, primefaces, primefaces-extensions, resteasy, resteasy-jackson, servlet, smallrye-context-propagation, smallrye-health, vertx, websockets, websockets-client]
```

**Comment by melloware** [comment]
Confirmed it looks like its related to this fix in Quarkus: https://github.com/quarkusio/quarkus/pull/32656

**Comment by melloware** [comment]
I submitted a fix: https://github.com/quarkusio/quarkus/pull/34611

**Comment by dstutz** [comment]
Looks like this will be the quarkus-undertow module and I assume 3.2.1 release at the earliest?  Thanks for looking into this, sorry I didn't get chance to test on Linux (work 🤷‍♂️ ).

**Comment by melloware** [comment]
I guess it all depends on when/if the Quarkus team merges it!

**Comment by melloware** [comment]
Related to this I finally got to the bottom of this problem: https://github.com/quarkusio/quarkus/issues/28028

But hopefully Quarkus Team will have some idea how to fix it.

**Comment by melloware** [comment]
OK looks like its slated for 3.3.0 from how they marked the ticket.

**Comment by melloware** [comment]
Confirmed 3.3.0.Final has fixed this issue!

**Comment by tonyherstell** [comment]
Thanks melloware and team
