### ISSUE TITLE
Not compatible with quarkus-spring-data-jpa successfully

### ISSUE THREAD

**Issue by dengbingaliyun** [melloware/quarkus-faces#284]
I added quarkus  spring data jpa dependency
```
<dependency> 
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-spring-data-jpa</artifactId>
</dependency>
```

the exception list below:

```
2023-06-11 08:56:07,232 WARN  [io.qua.agr.dep.AgroalProcessor] (build-22) The Agroal dependency is present but no JDBC datasources have been defined.
2023-06-11 08:56:09,741 WARN  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-35) Unable to determine a database type for default datasource
2023-06-11 08:56:09,744 WARN  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-35) Hibernate ORM is disabled because no JPA entities were found
2023-06-11 08:56:10,116 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-06-11 08:56:10,660 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Bean class org.primefaces.showcase.view.data.tree.LazyLoadingView declares multiple scope type annotations: jakarta.faces.view.ViewScoped, jakarta.inject.Singleton
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:324)
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1261)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1121)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:266)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:142)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:443)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Bean class org.primefaces.showcase.view.data.tree.LazyLoadingView declares multiple scope type annotations: jakarta.faces.view.ViewScoped, jakarta.inject.Singleton
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:324)
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1261)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1121)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:266)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:142)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:443)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
	... 9 more
Caused by: jakarta.enterprise.inject.spi.DefinitionException: Bean class org.primefaces.showcase.view.data.tree.LazyLoadingView declares multiple scope type annotations: jakarta.faces.view.ViewScoped, jakarta.inject.Singleton
	at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:324)
	at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1261)
	at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
	at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1121)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:266)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:142)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:443)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by melloware** [comment]
You can see here in the code : https://github.com/melloware/quarkus-faces/blob/main/src/main/java/org/primefaces/showcase/view/data/tree/LazyLoadingView.java

It only declares ViewScoped.   

I would not use Spring Data. To me it's not worth introducing Spring for reasons just like the phantom error you are getting above. 

If you need Spring Data why not just use something more Quarkus and EE friendly like Panache?
