### ISSUE TITLE
Native Build - PatternSyntaxException: Illegal/unsupported escape sequence

### ISSUE THREAD

**Issue by raamkumarak** [melloware/quarkus-faces#315]
### **Native Build Fails with below error** (mvn package -Dnative) .. Attached GraalVM Native Image Error Report. 
[svm_err_b_20230926T102541.572_pid62.md](https://github.com/melloware/quarkus-faces/files/12726540/svm_err_b_20230926T102541.572_pid62.md)

java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 27
META-INF/resources/ui\ajax\listener.xhtml
                           ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.escape(Pattern.java:2608)
	at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.makeResourcePattern(ResourcesFeature.java:361)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.compilePatterns(ResourcesFeature.java:354)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:337)
	
### **Environment Details**
1.  Microsoft Windows [Version 10.0.22621.2283]
2.  Apache Maven 3.9.3
3.  Java version: 17.0.8
4.  Docker version 23.0.5
5.  Quarkus 3.4.1

**Comment by melloware** [comment]
Let me test this.  Native Build was previously working fine.

**Comment by melloware** [comment]
I wonder if its Windows related because I can't reproduce it on Linux.

**Comment by melloware** [comment]
ahh open Quarkus issue: https://github.com/quarkusio/quarkus/issues/32272
