### ISSUE TITLE
Native compile error: Discovered unresolved method during parsing: jakarta.el.ELResolver.getFeatureDescriptors

### ISSUE THREAD

**Issue by redddcyclone** [melloware/quarkus-faces#492]
Hello,

First of all, I can't say this issue is not exactly related to quarkus-faces, but I used it as reference and couldn't think of a better place to ask for help with the following problem.

I'm getting these errors when trying to build a native image for my project with myfaces-quarkus 4.0.2 and quarkus-primefaces 3.14.6.3:

```
Error: Unsupported features in 2 methods
Detailed message:
Error: Discovered unresolved method during parsing: jakarta.el.ELResolver.getFeatureDescriptors(jakarta.el.ELContext, java.lang.Object). This error is reported at image build time because class org.apache.myfaces.component.validate.CopyBeanInterceptorELResolver is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.myfaces.component.validate.CopyBeanInterceptorELResolver.getFeatureDescriptors(CopyBeanInterceptorELResolver.java:80)
Parsing context:
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: jakarta.el.ELResolver.getFeatureDescriptors(jakarta.el.ELContext, java.lang.Object). This error is reported at image build time because class org.primefaces.el.InterceptingResolver is registered for linking at image build time by command line and command line.
Error encountered while parsing org.primefaces.el.InterceptingResolver.getFeatureDescriptors(InterceptingResolver.java:77)
Parsing context:
   at root method.(Unknown Source)
```

I see @melloware had already reported this at https://issues.apache.org/jira/browse/MYFACES-4579, but I couldn't solve this problem on my own.

Do you know what might be causing this?

Thanks in advance!

**Comment by melloware** [comment]
@redddcyclone what the issue was is that somehow you have a dependency in your pom.xml bringing in the wrong EL like "Nevermind Had to remove GlassFish EL it looks like MyFaces includes JASPER EL 11.0.0-M1"

**Comment by melloware** [comment]
If you can provide your pom.xml it may help?

**Comment by redddcyclone** [comment]
I see that the package jakarta.el-api version 5.0.1 (which contains the method described in the error) is brought by quarkus-reactive-routes and quarkus-narayana-jta. I already tried excluding this dependency from both dependencies but the problem still happens. I'll post the pom.xml in a few minutes

**Comment by melloware** [comment]
thx

**Comment by redddcyclone** [comment]
pom.xml is as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>com.blahblah</groupId>
    <artifactId>blah</artifactId>
    <version>7.0.0</version>
    <name>Blah</name>
    <description>Project</description>

    <properties>
    
    	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    	
		<maven.compiler.release>21</maven.compiler.release>
		
		<jasperreports.version>0.0.5</jasperreports.version>
		
		<quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
		<quarkus.platform.version>3.15.1</quarkus.platform.version>
        <compiler-plugin.version>3.13.0</compiler-plugin.version>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <skipITs>true</skipITs>
    </properties>

    <dependencyManagement>
        <dependencies>
        
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
			
        </dependencies>
    </dependencyManagement>
    
    <dependencies>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.myfaces.core.extensions.quarkus</groupId>
            <artifactId>myfaces-quarkus</artifactId>
            <version>4.0.2</version>
        </dependency>
        
        <dependency>
        	<groupId>io.quarkus</groupId>
        	<artifactId>quarkus-resteasy</artifactId>
        </dependency>
        
		<dependency>
    		<groupId>io.quarkus</groupId>
    		<artifactId>quarkus-reactive-routes</artifactId>
		</dependency>
		
		<dependency>
    		<groupId>io.quarkus</groupId>
    		<artifactId>quarkus-security-jpa</artifactId>
		</dependency>
		
		<dependency>
    		<groupId>io.quarkus</groupId>
    		<artifactId>quarkus-smallrye-jwt</artifactId>
		</dependency>
		<dependency>
    		<groupId>io.quarkus</groupId>
    		<artifactId>quarkus-smallrye-jwt-build</artifactId>
		</dependency>
		
		<dependency>
 			<groupId>io.quarkus</groupId>
	  		<artifactId>quarkus-resteasy-jsonb</artifactId>
		</dependency>
        
        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
            <version>2.1.3</version>
        </dependency>
        
		<dependency>
			<groupId>io.quarkiverse.primefaces</groupId>
			<artifactId>quarkus-primefaces</artifactId>
			<version>3.14.6.3</version>
		</dependency>
		<dependency>
		    <groupId>com.googlecode.owasp-java-html-sanitizer</groupId>
		    <artifactId>owasp-java-html-sanitizer</artifactId>
		    <version>20240325.1</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>font-awesome</artifactId>
			<version>6.5.2</version>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>primeflex</artifactId>
			<version>3.3.1</version>
		</dependency>
		
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-orm</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jdbc-postgresql</artifactId>
		</dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-narayana-jta</artifactId>
        </dependency>
		
		<dependency>
			<groupId>io.quarkiverse.jasperreports</groupId>
			<artifactId>quarkus-jasperreports</artifactId>
			<version>${jasperreports.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.groovy</groupId>
			<artifactId>groovy</artifactId>
			<version>4.0.22</version>
		</dependency>
		<dependency>
			<groupId>net.sourceforge.barbecue</groupId>
			<artifactId>barbecue</artifactId>
			<version>1.5-beta1</version>
		</dependency>
        
    </dependencies>
    
    <repositories>
    
		<repository>
			<id>local-repo</id>
			<url>file:///${project.basedir}/local-repo</url>
		</repository>
		
	</repositories>

    <build>
    
    	<finalName>${project.name}</finalName>
    	
    	<resources>
    	
    		<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
			</resource>
			
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.properties</include>
					<include>**/*.xml</include>
				</includes>
			</resource>
			
		</resources>
    
        <plugins>
        
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                            <goal>native-image-agent</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
					
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
                    
                </configuration>
            </plugin>
            
        </plugins>
        
    </build>

    <profiles>
    
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <properties>
                <skipITs>false</skipITs>
                <quarkus.native.enabled>true</quarkus.native.enabled>
            </properties>
        </profile>
        
    </profiles>
    
</project>
```

**Comment by redddcyclone** [comment]
Should I remove tomcal-el-api 11.0.0-M1 instead? Maybe I actually tried excluding the wrong dependency

**Comment by redddcyclone** [comment]
@melloware I excluded tomcat-el-api 11.0.0-M1 from myfaces-quarkus itself, as in:

```
<dependency>
    <groupId>org.apache.myfaces.core.extensions.quarkus</groupId>
    <artifactId>myfaces-quarkus</artifactId>
    <version>4.0.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-el-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

After doing this, the native image was built just fine. Do you think something should be done about this in myfaces-quarkus and/or quarkus-primefaces?

Anyway, I'm gonna test the image now. Thanks a lot for your help as always!

**Comment by melloware** [comment]
Yep I am going to fix it in MyFaces. It should NOT be including JASPER EL it should be deferring toi Quarkus.

**Comment by melloware** [comment]
I was able to reproducer your bug here: https://github.com/quarkiverse/quarkus-primefaces/actions/runs/11501165271/job/32013126752  I just added Reactive Routes and got the issue!

**Comment by melloware** [comment]
@redddcyclone i opened this MYFACES ticket to get it fixed: https://issues.apache.org/jira/browse/MYFACES-4687

**Comment by melloware** [comment]
PR submitted that fixes this: https://github.com/apache/myfaces/pull/773

**Comment by redddcyclone** [comment]
Great, thanks a lot for fixing this bug! Should I close this issue or leave it open for the time being?

**Comment by melloware** [comment]
lets leave this open for others to see until the next MyFaces releases comes out and then I will update this ticket.

**Comment by melloware** [comment]
MyFaces 4.1.0-RC3 is release so you can switch to it and remove most of your changes.

**Comment by redddcyclone** [comment]
@melloware thanks a lot for the fix!

**Comment by redddcyclone** [comment]
Hi @melloware 

I updated Quarkus to the latest version (3.25.3) and this exact same issue showed up again **(Discovered unresolved method during parsing: jakarta.el.ELResolver.getFeatureDescriptors)**. Now, MyFaces version does not matter. It happens even if I go back to 4.0.2. If I add back the tomcat-jasper-el exclusion, like when it fixed this problem back on 4.0.2, this error below occurs:

```
[ERROR] 	[error]: Build step org.apache.myfaces.core.extensions.quarkus.deployment.MyFacesProcessor#registerForLimitedReflection threw an exception: java.lang.NoClassDefFoundError: org/apache/el/ExpressionFactoryImpl
[ERROR] 	at org.apache.myfaces.core.extensions.quarkus.deployment.MyFacesProcessor.registerForLimitedReflection(MyFacesProcessor.java:495)
[ERROR] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:889)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:255)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.el.ExpressionFactoryImpl
[ERROR] 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[ERROR] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
[ERROR] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
[ERROR] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
[ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:577)
[ERROR] 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:524)
[ERROR] 	... 11 more
```

After some tests trying to compile a native image with every possible Quarkus version after the one I was using before, 3.18.2, I can confirm that **this started to happen on version 3.24.1**. Up to 3.23.4, my project compiled just fine. What could be causing this?

For reference, in my pom.xml I have the following dependencies managed by quarkus-bom:
```
quarkus-rest-jackson
quarkus-reactive-routes
quarkus-smallrye-jwt
quarkus-mailer
quarkus-hibernate-orm
quarkus-jdbc-postgresql
commons-text
```

Other dependencies not related to Quarkus version are:
```
myfaces-quarkus 4.1.1
quarkus-primefaces 3.15.6
font-awesome 6.7.2
primeflex 3.3.1
quarkus-jasperreports 1.0.7
```

**Comment by melloware** [comment]
@redddcyclone the issue is Quarkus 3.25 moved to EE 11 and Grizzly 6.0 which is the EE11 EL Resolver.

MyFaces 4.1 is EE10 and still uses Grizzly 5.0.  There is an API change and until MyFaces 5.0 is released you must stay on Quarkus 3.24.5+

**Comment by melloware** [comment]
Let me try latest 3.24.

**Comment by redddcyclone** [comment]
The error happens from 3.29.0 to 3.29.3.

Also, I got the following when trying to build the native image, even on 3.28:
```
Fatal error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'jakarta.faces.component.UIData$1' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
```

Well, I'll be absent for the next 4 days, so I can't do more tests for now... I'll be back on Monday

**Comment by melloware** [comment]
Yep I just cced you on another ticket i personally would not go near 25 until Quarkus fully supports 25

**Comment by redddcyclone** [comment]
Right, as of now I haven't got any more problems after adding these build arguments. I'll keep testing though

**Comment by melloware** [comment]
I haven't found a better way around it other than to add helper methods in my controllers to return counts etc.
